name: Develop PR Test

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./test-results

      - name: Convert test results to JUnit format
        run: dotnet tool install --global trx2junit && trx2junit ./test-results/test_results.trx

      - name: 📑 Publish Test Results as PR Comment
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/test-results/test_results.junit.xml'

      - name: ✅ Add Check Comments for Failed Code Lines
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results/test_results.junit.xml'
          token: ${{ github.token }}
